version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: padrerico-app
    container_name: padrerico-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=padrerico
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - padrerico

  db:
    image: mariadb:11
    container_name: padrerico-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: padrerico
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - padrerico

  nginx:
    image: nginx:alpine
    container_name: padrerico-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - padrerico

volumes:
  dbdata:

networks:
  padrerico:
    driver: bridge
